image: Visual Studio 2017
configuration: Release

environment:
   semVersion: 2.3.0

branches:
  except:
  - gh-pages

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2017

build_script: 
  - ps: .\build.ps1

test: off
deploy: off

artifacts: 
  - path: 'artifacts/**/*.nupkg'
  - path: 'artifacts/docs'
